export const BRAND_INFO = {
  name: 'PRTN™',
  tagline: 'PURE VOLTAGE PROTEIN',
  heroLine1: ['P', 'U', 'R', 'E'],
  heroLine2: ['P', 'R', 'T', 'N'],
  edition: 'SERIES 01 // PERFORMANCE',
  batch: 'ISOLATE // LOT #882',
  volume: '330 ML / 11.2 FL OZ',
  formula: '30G MICRO-FILTERED HYDROLYZED PEPTIDES',
  macros: '30G PROTEIN • 0G SUGAR • 130 KCAL',
  ph: 'pH 6.8 BIO-NEUTRAL',
  temp: 'SERVE CHILLED AT 3°C',
};

export const EDITIONS = [
  {
    id: 'hydro-isolate',
    category: 'CATEGORY 01',
    name: '01 / HYDRO WHEY ISOLATE',
    shortName: 'HYDRO ISOLATE',
    tag: 'MAX ABSORPTION',
    color: '#B7FF00',
    accentColor: '#84CC16',
    liquidColor: '#c8ff2e',
    capColor: '#0a0a0a',
    glassTint: '#e8ffb0',
    transmission: 0.94,
    protein: '30G Hydrolyzed Whey',
    bcaa: '6.8G Branched Aminos',
    leucine: '3.2G Key Activator',
    flavor: 'Glacial Yuzu + Matcha Crisp',
    profile: 'Ultra-fast gastric clearance designed for immediate post-training muscle protein synthesis.',
    notes: ['Japanese Yuzu Zest', 'Ceremonial Matcha', 'Cold Alpine Spring', 'Bio-Available Leucine'],
    status: 'IN STOCK // DISPATCH TODAY',
  },
  {
    id: 'plant-peptides',
    category: 'CATEGORY 02',
    name: '02 / RAW PLANT PEPTIDE',
    shortName: 'PLANT PEPTIDE',
    tag: '100% ORGANIC VEGAN',
    color: '#38BDF8',
    accentColor: '#0284C7',
    liquidColor: '#0c2233',
    capColor: '#d4d4d8',
    glassTint: '#1c2d3d',
    transmission: 0.82,
    protein: '28G Fermented Seed Complex',
    bcaa: '5.9G Plant Aminos',
    leucine: '2.8G Bio-fermented',
    flavor: 'Obsidian Cacao + Lion\'s Mane Extract',
    profile: 'Hypoallergenic fermented pumpkin seed, sacha inchi, and yellow pea peptides with adaptogenic mushrooms.',
    notes: ['Wild Ecuadorian Cacao', 'Organic Lion\'s Mane', 'Smoked Birch Bark', 'Mineral Electrolytes'],
    status: 'LIMITED PRODUCTION // 800 CRATES',
  },
  {
    id: 'clear-collagen',
    category: 'CATEGORY 03',
    name: '03 / CLEAR COLLAGEN & EAA',
    shortName: 'CLEAR COLLAGEN',
    tag: 'JOINT & CELLULAR MATRIX',
    color: '#FF0055',
    accentColor: '#E11D48',
    liquidColor: '#ff255a',
    capColor: '#d4af37',
    glassTint: '#ffe4ea',
    transmission: 0.92,
    protein: '25G Marine Collagen Type I & III',
    bcaa: '6.2G Full Spectrum EAAs',
    leucine: '3.0G Free-Form EAA',
    flavor: 'Blood Dragonfruit + Hibiscus Infusion',
    profile: 'Crystal-clear bioactive collagen peptides paired with all 9 essential amino acids for tendon elasticity and cellular repair.',
    notes: ['Sicilian Blood Orange', 'Wild Red Dragonfruit', 'Cold-Steeped Hibiscus', 'Hyaluronic Acid'],
    status: 'PRE-ORDER // SERIES 02',
  }
];

export const INGREDIENTS = [
  { name: 'Cold Micro-Filtered Whey Peptides', pct: '30.0G', desc: 'Enzymatically hydrolyzed for instant bioavailability' },
  { name: 'Active BCAA / Leucine Matrix', pct: '6.8G', desc: '2:1:1 pharmaceutical ratio triggers rapid mTOR pathway' },
  { name: 'Marine Deep-Sea Electrolytes', pct: '1,200MG', desc: 'Potassium, Magnesium, and Pink Himalayan minerals' },
  { name: 'Organic Cold-Pressed Botanical Flavor', pct: '1.2G', desc: 'Natural fruit oils and ceremonial extracts, 0g synthetic additives' },
  { name: 'Purified Glacial Spring Water Base', pct: '290ML', desc: 'Sourced from volcanic strata, pH 6.8 balanced' },
];

export const MACRO_METRICS = [
  { label: 'PROTEIN PURITY', value: '30g', detail: 'ZERO GUMS OR FILLERS' },
  { label: 'SUGARS / CARBS', value: '0.0g', detail: 'KETO & DIABETIC SAFE' },
  { label: 'BCAA PROFILE', value: '6.8g', detail: 'OPTIMAL 2:1:1 RATIO' },
  { label: 'NET CALORIES', value: '130', detail: 'LEAN METABOLIC CHARGE' },
];

export const NAV_LINKS = [
  { label: 'MANIFESTO', href: '#story' },
  { label: 'AI BIO-ENGINE', href: '#ai-engine' },
  { label: 'SPECS & MACROS', href: '#specs' },
  { label: '3 CATEGORIES', href: '#showcase' },
  { label: 'ORDER [CRATE]', href: '#shop' },
];
